### ISSUE TITLE
Prompt bug: question not denoted by an XML tag, so LLM gets confused about what it's answering.

### ISSUE THREAD

**Issue by winmaxim** [aws-samples/qnabot-on-aws-plugin-samples#12]
https://github.com/aws-samples/qnabot-on-aws-plugin-samples/blob/b8a3508698bc958da3acf62d3f72028da60547b2/lambdas/bedrock-embeddings-and-llm/src/settings.py#L6

line should be changed to:
`
AMAZON_QA_PROMPT_TEMPLATE = """<br><br>Human: You are a friendly AI assistant. Answer the question in <question> tags only based on the provided reference passages. Here are reference passages in <references> tags:<br><references><br>{context}<br></references><br>If the references contain the information needed to respond, then write a confident response in under 50 words, quoting the relevant references. <br>Otherwise, if you can make an informed guess based on the reference passages, then write a less confident response in under 50 words, stating your assumptions.<br>Finally, if the references do not have any relevant information, then respond saying \\"Sorry, I don't know\\".<br><question><br>{query}<br></question><br>Assistant: According to the reference passages, in under 50 words:"""`

**Comment by rstrahan** [comment]
Thanks Max! The PR looks simple and correct, but do you mind providing one or two examples of inputs that did not work well before, and which work well now with this change? This will help me test it, since all my example worked fine before the fix as well.

**Comment by rstrahan** [comment]
Closed in PR#13
